apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v9pa0jxp5-nodejs 
  janus-idp.io/tekton: v9pa0jxp5-nodejs
  backstage.io/kubernetes-id: v9pa0jxp5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v9pa0jxp5-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml